### ISSUE TITLE
Create a quickstart guide

### ISSUE THREAD

**Issue by RazZziel** [hicknhack-software/QSqlMigrator#14]
At first glance it's difficult to see how QSqlMigrator can help my project; I think users would greatly appreciate some sort of quickstart guide with a simple example on how the library is supposed to be used.

I think a good example is the readme of https://github.com/sandeepmistry/bleno

**Comment by arBmind** [comment]
Thank you for the report. I have updated the Readme.md and added a basic usage example.

Please report if this meets your expectations.

**Comment by RazZziel** [comment]
That's awesome, thanks!!
